from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.16.0")


configfile: "config/config.yml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/download.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/model.smk"
include: "rules/qc.smk"


rule all:
    input:
        expand(
            rules.model_report.output,
            db=list(config["KNRGL"].keys()),
            ref=config["genome"]["build"],
            outdir=config["outdir"],
        ),
        expand(
            rules.reads_multiqc.output,
            outdir=config["outdir"],
        ),
        expand(
            rules.aln_multiqc.output,
            ref=config["genome"]["build"],
            outdir=config["outdir"],
        ),
        expand(
            rules.classes_db_ref.output,
            outdir=config["outdir"],
        ),
