from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.16.0")


configfile: "config/config.yml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/download.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/model.smk"


rule all:
    input:
        expand(
            rules.metrics.output,
            ref=config["genome"]["build"],
            dna_type="mda",
        ),
    wildcard_constraints:
        dna_type="\w+",
