channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.11
  - ipykernel
  - pandas>=2
  - seaborn>=0.13.0
  - git>=2
  - git-lfs
  - samtools>=1.18
  - bcftools>=1.18
  - bedtools>=2.31.0
  - snakemake==8.10.7
  - snakefmt
  - conda-lock==2.5.7
  - dvc
  - pyarrow
  - biopython
  - scikit-learn>=1.4
  - flaml>=2.1.2
  - datashader
  - nbdime
  - igv>=2.17.4
  - picard
  - reportlab
  - black-jupyter
  - pysam>=0.22.1
  - bedops
  - pyranges==0.1.2
  - bionumpy>=1
  - pip:
    - ipynb==0.5.1
