channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10
  - ipykernel
  - pandas>=2
  - seaborn>=0.13.0
  - git>=2
  - git-lfs
  - samtools>=1.18
  - bcftools>=1.18
  - bedtools>=2.31.0
  - snakemake==8.10.7
  - snakefmt
  - conda-lock==2.5.7
  - dvc
  - pyarrow
  - biopython
  - scikit-learn>=1.4
  - flaml>=2.1.2
  - datashader
  - nbdime
