# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: .test/config_sample/test.tsv

ref: 
  build: hs37d5 # options: <hs37d5>
  region: all # all = use all regions. When specifying other regions, ensure compatible with build
  database: eul1db # options: eul1db or a csv file (chrom, start, end, in_NRdb=True)
  # located under resources/{database}/windows.csv

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 2
  min_reads: 3
  fold_window: 20_000_000
  window_size: 750
  prob: 0.7
