samples: .test/chr21chr22/samples.tsv
donors: .test/chr21chr22/donors.tsv
outdir: .test

genome:
  ftp: ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
  name: hs38DH
  region: [chr21, chr22]

folds:
  split_by: "donor_id"
  num_folds: 2
  min_reads: 1
