# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/all_samples.tsv
donors: config/all_donors.tsv
outdir: /iblm/netapp/data4/mcuoco/sz_slavseq

genome:
  ftp: ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
  name: hs38d1
  region: all

adapters:
  p7_i7: 'AATGATACGGCGACCACCGAGATCTACACNNNNNNNN'
  r1: 'ACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  p5_i5: 'CAAGCAGAAGACGGCATACGAGANNNNNNNN'
  r2: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  L1_nested: "TAACTAACCTGCACAATGTGCAC"
  L1_downstream: "ATGTACCCTAAAACTTAGAGTATAATAAAAAAAAAAAAA"

get_features:
  window_size: 750
  window_step: 250
