# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/single_donor.tsv
outdir: results

genome:
  build: [hs37d5, hs38DH, chm13v2] # options: <hs37d5|hs38DH|chm13v2>
  region: all # for chromosome 22: use "22" for hs37d5, use "chr22" for hs38DH and chm13v2

KNRGL:
  dbVar:
    build: hs38DH
  eul1db:
    build: hg19

adapters:
  r1_adapter: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  r2_adapter: "CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  nested_primer: "TAACTAACCTGCACAATGTGCAC"

get_features:
  min_reads: 3
  window_size: 750
  window_step: 250
  min_mapq: 40
  min_ya: 20
  max_yg: 15
  min_secondary_mapq: 20
  library_3_or_5: 3

num_folds: 4

models:
  rfc_1:
    name: "RandomForestClassifier"
    params:
      random_state: 1
      n_jobs: -1
  mlp_1:
    name: "MLPClassifier"
    params:
