# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/four_donors.tsv
outdir: /raidixshare_logg01/mcuoco/internal/BSMN

genome:
  build: [hs37d5, hs38DH, chm13v2] # options: <hs37d5|hs38DH|chm13v2>
  region: all # for chromosome 22: use "22" for hs37d5, use "chr22" for hs38DH and chm13v2

KNRGL:
  dbVar:
    build: hs38DH
  eul1db:
    build: hg19

adapters:
  r1_adapter: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  r2_adapter: "CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  nested_primer: "TAACTAACCTGCACAATGTGCAC"

get_features:
  min_reads: 5
  window_size: 750
  window_step: 250
  min_mapq: 40
  min_ya: 20
  max_yg: 15
  min_secondary_mapq: 20
  library_3_or_5: 3

num_folds: 4

# Do not set n_jobs > 8
models:
  rfc:
    name: "RandomForestClassifier"
    params:
      random_state: 1
      n_jobs: 8
  cfc:
    name: "CascadeForestClassifier"
    params:
      n_jobs: 8
  mlp_10_3:
    name: "MLPClassifier"
    params:
      hidden_layer_sizes:
        - 10
        - 3
  logreg_elastic:
    name: "LogisticRegression"
    params:
      solver: 'saga'
      penalty: 'elasticnet'
      n_jobs: 8
      l1_ratio: 0.5
  # svc: 
  #   name: "SVC"
  #   params:
    
    
