# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/single_donor.tsv

genome:
  build: hs37d5 # options: <hs38DH|hs37d5>
  region: all # use 22 for hs37d5

germline_line1: # given by eul1db or a BED file (resources/{source}/insertions.bed)
   source: eul1db
   build: hg19

# basename of chain file (None if no liftover expected)
chain: None

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 4
  min_reads: 3
  fold_window: 2_000_000
  window_size: 750
  prob: 0.7
