# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/single_donor.tsv

ref:
  build: hs37d5 # options: <hs38|hs38a|hs38DH|hs37|hs37d5>
  region: all # all = use all regions. When specifying other regions, ensure compatible with build
  database: eul1db # options: eul1db

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 4
  min_reads: 3
  fold_window: 2_000_000
  window_size: 750
  prob: 0.7
