# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
individuals: config/individuals.tsv
# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
cells: config/cells.tsv

ref: hs37d5 # options: hsd37d5 or GRCh38