# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/single_donor.tsv

genome:
  build: hs37d5 # options: <hs37d5|hs38DH|chm13v2>
  region: all # for chromosome 22: use "22" for hs37d5, use "chr22" for hs38DH and chm13v2

non_ref_germline_l1: # given by eul1db or a BED file (resources/{source}/insertions.bed)
   source: eul1db
   build: hg19

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 4
  min_reads: 3
  fold_window: 2_000_000
  window_size: 750
  window_step: 250
  prob: 0.7
