# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/four_donors.tsv
outdir: /raidixshare_logg01/mcuoco/internal/BSMN

genome:
  build: hs38DH # options: <hs37d5|hs38DH|chm13v2>
  region: all # for chromosome 22: use "22" for hs37d5, use "chr22" for hs38DH and chm13v2

KNRGL:
  dbVar:
    build: hs38DH

adapters:
  r1_adapter: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  r2_adapter: "CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  nested_primer: "TAACTAACCTGCACAATGTGCAC"

get_features:
  min_reads: 5
  window_size: 750
  window_step: 250
  min_mapq: 40
  min_ya: 20
  max_yg: 15
  min_secondary_mapq: 20
  library_3_or_5: 3

folds:
  split_by: "donor_id"
  num_folds: 4
  downsample_train: True
  downsample_test: True

# Do not set n_jobs > 8
models:
  RandomForestClassifier10:
    name: "RandomForestClassifier"
    params:
      n_estimators: 10
