# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: config/single_donor.tsv
outdir: /raidixshare_logg01/mcuoco/internal/BSMN

genome:
  url: ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
  name: hs38DH
  region: all

KNRGL:
  dbVar:
    build: hs38DH

adapters:
  r1_adapter: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  r2_adapter: "CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  nested_primer: "TAACTAACCTGCACAATGTGCAC"

get_features:
  window_size: 750
  window_step: 250
  min_reads: 3

folds:
  split_by: "cell_id"
  num_folds: 4
  test_sampling_strategy: "auto"

# Do not set n_jobs > 8
models:
  RFC10:
    name: "RandomForestClassifier"
    train_sampling_strategy: "auto"
    params:
      n_estimators: 10
      random_state: 1
