# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: .test/config_chr22/test.tsv

ref:
  build: hs37d5 # options: <hs38DH|hs37d5>
  region: "22" # use 22 for hs37d5, use chr22 for hs38DH
  database: eul1db

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 2
  min_reads: 3
  fold_window: 20_000_000
  window_size: 750
  prob: 0.7
