samples: .test/config/samples.tsv
donors: .test/config/donors.tsv
outdir: .test

genome:
  fasta: ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
  rmsk: hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz
  name: hs38d1
  region: [chr21, chr22]

folds:
  split_by: "donor_id"
  num_folds: 2
  min_reads: 1
