samples: config/samples.tsv
donors: config/donors.tsv
outdir: /iblm/logglun02/mcuoco/workflows/sz_slavseq/.test

genome:
  fasta: resources/chr2122/chr2122.fasta
  bwa: resources/chr2122/BWA/chr2122.fasta
  rmsk: resources/chr2122/chr2122.fasta.out
  xtea: resources/chr2122/wgs_calls/xtea_LINE1.vcf
  megane_percentile: resources/chr2122/wgs_calls/megane_MEIs.vcf
  megane_gaussian: resources/chr2122/wgs_calls/megane_MEIs.vcf
  name: chr2122

adapters:
  p7_i7: 'AATGATACGGCGACCACCGAGATCTACACNNNNNNNN'
  r1: 'ACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  p5_i5: 'CAAGCAGAAGACGGCATACGAGANNNNNNNN'
  r2: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  L1_nested: "TAACTAACCTGCACAATGTGCAC"
  L1_downstream: "ATGTACCCTAAAACTTAGAGTATAATAAAAAAAAAAAAA"

bulk_peaks_params:
  size: 200
  step: 1
  minreads: 3
  minrpm: 1
