# path or URL to sample sheet (TSV format, columns: donor, sample, dna_type,...)
samples: .test/config/test.tsv

ref: 
  build: hs37d5 # options: <hs38|hs38a|hs38DH|hs37|hs37d5>
  region: 22 # use 22 for hs37d5

adapters:
  r1_adapter: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  r2_adapter: 'CAAGCAGAAGACGGCATACGAGANNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
  nested_primer: 'TAACTAACCTGCACAATGTGCAC'

model:
  num_folds: 4
  min_reads: 3
  window_size: 2_000_000
