samples: config/samples.tsv
donors: config/donors.tsv
outdir: /iblm/netapp/data3/mcuoco/sz_slavseq/.test

genome:
  fasta: resources/chr2122/chr2122.fasta
  fai: resources/chr2122/chr2122.fasta.fai
  bwa: resources/chr2122/BWA/chr2122.fasta
  rmsk: resources/chr2122/chr2122.fasta.out
  xtea: data/xtea_LINE1.vcf
  megane_percentile: data/usd7_LINE1.vcf
  megane_gaussian: data/usd7_LINE1.vcf
  name: chr2122
  size: 3117292070

adapters:
  p7_i7: "AATGATACGGCGACCACCGAGATCTACACNNNNNNNN"
  r1: "ACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  p5_i5: "CAAGCAGAAGACGGCATACGAGANNNNNNNN"
  r2: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  L1_nested: "TAACTAACCTGCACAATGTGCAC"
  L1_downstream: "ATGTACCCTAAAACTTAGAGTATAATAAAAAAAAAAAAA"
