samples: config/samples.tsv
donors: config/donors.tsv
outdir: /iblm/logglun02/mcuoco/workflows/sz_slavseq/.test

genome:
  fasta: resources/chr2122/chr2122.fasta
  bwa: resources/chr2122/BWA/chr2122.fasta
  rmsk: resources/chr2122/chr2122.fasta.out
  name: chr2122

adapters:
  p7_i7: 'AATGATACGGCGACCACCGAGATCTACACNNNNNNNN'
  r1: 'ACACTCTTTCCCTACACGACGCTCTTCCGATCT'
  p5_i5: 'CAAGCAGAAGACGGCATACGAGANNNNNNNN'
  r2: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  L1_nested: "TAACTAACCTGCACAATGTGCAC"
  L1_downstream: "ATGTACCCTAAAACTTAGAGTATAATAAAAAAAAAAAAA"

get_features:
  split_by: "donor_id"
  num_folds: 2
  min_reads: 1
