$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
  samples:
    type: string
  donors:
    type: string

  genome:
    type: object
    properties:
      fasta:
        type: string
      bwa:
        type: string
      rmsk:
        type: string
      xtea:
        type: string
      megane_percentile:
        type: string
      megane_gaussian:
        type: string
      name:
        type: string
    required:
      - fasta
      - bwa
      - xtea
      - megane_percentile
      - megane_gaussian
      - name

  adapters:
    type: object

required:
  - outdir
  - genome
  - samples
  - donors
  - adapters
