$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  genome:
    type: object
    properties:
      build:
        type: string
      region:
        type: [integer, string, array]
        default: all
    required:
      - build

  non_ref_germline_l1:
    type: object
    properties:
      source:
        type: string
      build:
        type: string

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  model:
    type: object
    properties:
      type: 
        type: [string, array]
      num_folds:
        type: integer
      min_reads:
        type: integer
      fold_window:
        type: integer
      window_size:
        type: integer
      prob: 
        type: number

required:
  - samples
  - genome
  - adapters
  - model
  