$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  genome:
    type: object
    properties:
      build:
        type: string
      region:
        type: [integer, string, array]
        default: all
    required:
      - build

  non_ref_germline_l1:
    type: object
    properties:
      source:
        type: string
        enum: [eul1db, dbVar]
      build:
        type: string

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  get_features:
    type: object
    min_reads: 
      type: integer
    window_size: 
      type: integer
    window_step: 
      type: integer
    min_mapq: 
      type: integer
    min_ya: 
      type: integer
    max_yg: 
      type: integer
    min_secondary_mapq: 
      type: integer
    library_3_or_5: 
      type: integer
      enum: [3, 5]

  num_folds:
    type: integer

  models:
    type: object

required:
  - samples
  - genome
  - adapters
  - num_folds
  - get_features
  - models
  