$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  genome:
    type: object
    properties:
      build:
        type: string
      region:
        type: [integer, string, array]
        default: all
    required:
      - build

  non_ref_germline_l1:
    type: object
    properties:
      source:
        type: string
      build:
        type: string

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  get_features:
    min_reads: integer
    window_size: integer
    window_step: integer
    min_mapq: integer
    min_ya: integer
    max_yg: integer
    min_secondary_mapq: integer
    library_3_or_5: integer

  num_folds:
    type: integer

  models:
    type: object

required:
  - samples
  - genome
  - adapters
  - num_folds
  - get_features
  - models
  