$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
  samples:
    type: string
  donors:
    type: string

  genome:
    type: object
    properties:
      ftp:
        type: string
      name:
        type: string
      region:
        type: [string, array]

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  get_features:
    type: object
    min_reads:
      type: integer
    window_size:
      type: integer
    window_step:
      type: integer
    min_mapq:
      type: integer
    min_ya:
      type: integer
    max_yg:
      type: integer
    min_secondary_mapq:
      type: integer

required:
  - outdir
  - genome
  - samples
  - donors
  - adapters
  - get_features
