$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  genome:
    type: object
    properties:
      build:
        type: [ string, array ]
      region:
        type: string
        default: all
    required:
      - build

  non_ref_germline_l1:
    type: object
    properties:
      source:
        type: string
        default: eul1db
      build:
        type: string
        default: hg19

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  model:
    type: object
    properties:
      num_folds:
        type: integer
        default: 4
      min_reads:
        type: integer
        default: 3
      fold_window:
        type: integer
        default: 2_000_000
      window_size:
        type: integer
        default: 750
      prob: 
        type: number
        default: 0.7

required:
  - samples
  - genome
  - adapters
  - model
  