$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  genome:
    type: object
    properties:
      build:
        type: [string, array]
      region:
        type: [integer, string, array]
        default: all
    required:
      - build

  KNRGL:
    type: object

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  get_features:
    type: object
    min_reads:
      type: integer
    window_size:
      type: integer
    window_step:
      type: integer
    min_mapq:
      type: integer
    min_ya:
      type: integer
    max_yg:
      type: integer
    min_secondary_mapq:
      type: integer
    library_3_or_5:
      type: integer
      enum: [3, 5]

  folds:
    type: object
    split_by:
      type: string
    num_folds:
      type: integer
    downsample_train:
      type: boolean
    downsample_test:
      type: boolean

  models:
    type: object

required:
  - samples
  - genome
  - adapters
  - get_features
  - folds
  - models
