$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
  samples:
    type: string
  donors:
    type: string

  genome:
    type: object
    properties:
      fasta:
        type: string
      bwa:
        type: string
      rmsk:
        type: string
      xtea:
        type: string
      megane:
        type: string
      name:
        type: string
    required:
      - fasta
      - bwa
      - xtea
      - megane
      - name

  adapters:
    type: object

  bulk_peaks_params:
    type: object
    properties:
      size:
        type: integer
      step:
        type: integer
      strand_split:
        type: boolean
      min_rpm:
        type: integer
      min_reads:
        type: integer
    required:
      - size
      - step
      - min_rpm
      - min_reads

  peaks_params:
    type: object
    properties:
      size:
        type: integer
      step:
        type: integer
      strand_split:
        type: boolean
      min_rpm:
        type: integer
      min_reads:
        type: integer
    required:
      - size
      - step
      - min_rpm
      - min_reads

  windows_params:
    type: object
    properties:
      size:
        type: integer
      step:
        type: integer
      min_rpm:
        type: integer
      min_reads:
        type: integer
    required:
      - size
      - step
      - min_rpm
      - min_reads

required:
  - outdir
  - genome
  - samples
  - donors
  - adapters
  - bulk_peaks_params
  - peaks_params
  - windows_params
