$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
  samples:
    type: string
  donors:
    type: string

  genome:
    type: object
    properties:
      build:
        type: [string, array]
      region:
        type: [integer, string, array]
        default: all
    required:
      - build

  KNRGL:
    type: object

  adapters:
    type: object
    properties:
      r1_adapter:
        type: string
      r2_adapter:
        type: string
      nested_primer:
        type: string
    required:
      - r1_adapter
      - r2_adapter
      - nested_primer

  folds:
    type: object
    split_by:
      type: string
    num_folds:
      type: integer
    downsample_train:
      type: boolean
    downsample_test:
      type: boolean

  models:
    type: object

required:
  - outdir
  - samples
  - donors
  - genome
  - adapters
  - folds
  - models
