name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: mamba install -n snakemake -c conda-forge biopython -y -q 
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Formatting
    steps: 
    - uses: actions/checkout@v2
    - name: Test workflow on single sample
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: mamba install -n snakemake -c conda-forge biopython -y -q
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --all-temp --configfile .test/config_sample/config.yml --debug"
    - name: Test workflow on single individual
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: mamba install -n snakemake -c conda-forge biopython -y -q
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 8 --conda-cleanup-pkgs cache --all-temp --configfile .test/config_indv/config.yml"

    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"