name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          
  Testing: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        genome: ["hs37d5", "hs38DH", "chm13v2"]
    needs:
      - Formatting
    steps: 
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Run workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: |
          mamba install -n snakemake -c conda-forge biopython -y -q
        snakefile: workflow/Snakefile
        args: "all --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --all-temp --configfile .test/chr22/${{ matrix.genome }}.yml"

    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"