name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SNAKEMAKE_OUTPUT_CACHE: $GITHUB_WORKSPACE/snakemake_cache

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          
  Testing: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        genome: ["hs37d5", "hs38DH", "chm13v2"]
    needs:
      - Formatting
    steps: 
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Snakemake cache
      id: cache-sm
      uses: actions/cache@v3
      with:
        path: ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        key: ${{ runner.os }}-${{ matrix.genome }}-sm
    - name: Install Snakemake via mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        python-version: 3.9
        channels: conda-forge,bioconda,nodefaults
        channel-priority: strict
    - run: mamba install python=3.9 snakemake==7.16 biopython
    - name: Run workflow
      run: |
        mkdir -p ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        export SNAKEMAKE_OUTPUT_CACHE=${{ env.SNAKEMAKE_OUTPUT_CACHE }}
        snakemake all --use-conda --cache --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --all-temp --configfile .test/chr21chr22/${{ matrix.genome }}.yml

    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"