name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: mamba install -n snakemake -c conda-forge biopython -y -q 
        snakefile: workflow/Snakefile
        args: "--lint"

  Test Preprocessing:
    timeout-minutes: 1000
    runs-on: ubuntu-latest
    needs:
      - Linting
      - Formatting
    steps: 
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Test workflow through flank_features on chr22 data only
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: mamba install -n snakemake -c conda-forge biopython -y -q
        snakefile: workflow/Snakefile
        args: "--until results/flank_features/test/mda/chr22.pickle.gz --use-conda --show-failed-logs --cores 4 --conda-cleanup-pkgs cache --all-temp --configfile .test/config_chr22/config.yml"

  Test Model: 
    - name: Test workflow after flank_features, using pickle from full
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        stagein: |
          mamba install -n snakemake -c conda-forge biopython -y -q
          mkdir -p results/flank_features/test/mda/ && cp .test/data/USD7_F1_S92.pickle.gz results/flank_features/test/mda/test.pickle.gz
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 4 --conda-cleanup-pkgs cache --all-temp --configfile .test/config_model/config.yml"

    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v1.24.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"
